03-19 14:37:23 replicate_layout.action_replicate_layout 305:Plugin executed on: 'win32'
03-19 14:37:23 replicate_layout.action_replicate_layout 306:Plugin executed with python version: '3.9.6 (default, Sep 27 2021, 21:15:11) [MSC v.1929 64 bit (AMD64)]'
03-19 14:37:23 replicate_layout.action_replicate_layout 307:KiCad build version: (6.0.1)
03-19 14:37:23 replicate_layout.action_replicate_layout 308:Replicate layout plugin version: 77 started
03-19 14:37:23 replicate_layout.action_replicate_layout 339:Preparing replicator with J1 as a reference
03-19 14:37:23 replicate_layout.replicatelayout 141:getting a list of all footprints on board
03-19 14:37:23 replicate_layout.action_replicate_layout 345:Fatal error when making an instance of replicator
Traceback (most recent call last):
  File "C:\Users/Rio/Documents/KiCad/6.0/scripting\plugins\replicate_layout\action_replicate_layout.py", line 342, in Run
    replicator = replicatelayout.Replicator(board)
  File "C:\Users/Rio/Documents/KiCad/6.0/scripting\plugins\replicate_layout\replicatelayout.py", line 146, in __init__
    sheet_id = self.get_sheet_id_alt(fp)
  File "C:\Users/Rio/Documents/KiCad/6.0/scripting\plugins\replicate_layout\replicatelayout.py", line 122, in get_sheet_id_alt
    sheet_id = self.get_path(module).split("/")[-2]
IndexError: list index out of range
